# Exploring NumPy’s UFuncs

### Array arithmetic

In [1]:
import numpy as np

In [2]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]


In [3]:
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) ## floor division

x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [4]:
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [5]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [10]:
## ufunc negation

print("-x = ", -x)

-x =  [ 0 -1 -2 -3]


In [11]:
## x raise to power 2

print("x ** 2 = ", x ** 2)

x ** 2 =  [0 1 4 9]


In [13]:
## modulus

print("x % 2 = ", x % 2)

x % 2 =  [0 1 0 1]


In [14]:
## standard order maintained

-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

## operators in numpy

- \+ np.add Addition (e.g., 1 + 1 = 2)
- \- np.subtract Subtraction (e.g., 3 - 2 = 1)
- \- np.negative Unary negation (e.g., -2)
- \* np.multiply Multiplication (e.g., 2 * 3 = 6)
- / np.divide Division (e.g., 3 / 2 = 1.5)
- // np.floor_divide Floor division (e.g., 3 // 2 = 1)
- ** np.power Exponentiation (e.g., 2 ** 3 = 8)
- % np.mod Modulus/remainder (e.g., 9 % 4 = 1)

In [15]:
x

array([0, 1, 2, 3])

In [16]:
np.add(x, 2) ## add 2 to x

array([2, 3, 4, 5])

In [17]:
np.subtract(x, 1) ## subtract 1 from x

array([-1,  0,  1,  2])

In [18]:
np.multiply(x, 2)

array([0, 2, 4, 6])

In [19]:
np.divide(x, 3)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [20]:
np.power(x, 3)

array([ 0,  1,  8, 27], dtype=int32)

## Absolute values

In [21]:
y = np.array([-2,-1,0,1,2])

In [22]:
y


array([-2, -1,  0,  1,  2])

In [23]:
abs(y)

array([2, 1, 0, 1, 2])

In [24]:
## np 

np.absolute(y)

array([2, 1, 0, 1, 2])

In [25]:
## or

np.abs(y)

array([2, 1, 0, 1, 2])

In [26]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])

In [27]:
np.abs(x)

array([5., 5., 2., 1.])

## Trigonometry Functions

In [28]:
theta = np.linspace(0, np.pi, 3)

In [29]:
print("theta =", theta)

theta = [0.         1.57079633 3.14159265]


In [30]:
np.linspace?

In [31]:
np.pi?

In [32]:
print("sin(theta) = ", np.sin(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [33]:
print("cos(theta) = ", np.cos(theta))

cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [34]:
print("tan(theta) = ", np.tan(theta))

tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [35]:
## Inverse trig

x = [-1, 0, 1]
print("x = ", x)

x =  [-1, 0, 1]


In [36]:
print("arcsin(x) = ", np.arcsin(x))

arcsin(x) =  [-1.57079633  0.          1.57079633]


In [37]:
print("arccos(x) = ", np.arccos(x))

arccos(x) =  [3.14159265 1.57079633 0.        ]


In [38]:
print("arctan(x) = ", np.arctan(x))

arctan(x) =  [-0.78539816  0.          0.78539816]


In [39]:
## Exponents and logarithms

x = [1, 2, 3]
print("x =", x)

x = [1, 2, 3]


In [40]:
print("e^x =", np.exp(x))

e^x = [ 2.71828183  7.3890561  20.08553692]


In [41]:
print("2^x =", np.exp2(x))

2^x = [2. 4. 8.]


In [42]:
print("3^x =", np.power(3, x))

3^x = [ 3  9 27]


In [43]:
print("4^x =", np.power(4, x))

4^x = [ 4 16 64]


In [44]:
print("2^x =", np.power(2, x))

2^x = [2 4 8]


In [45]:
print("1^x =", np.power(1, x))

1^x = [1 1 1]


In [46]:
## inverse of the exponentials, the logarithms, are also available.

x = [1, 2, 4, 10]
print("x =", x)

x = [1, 2, 4, 10]


In [47]:
print("ln(x) =", np.log(x))

ln(x) = [0.         0.69314718 1.38629436 2.30258509]


In [48]:
print("log2(x) =", np.log2(x))

log2(x) = [0.         1.         2.         3.32192809]


In [49]:
print("log10(x) =", np.log10(x))

log10(x) = [0.         0.30103    0.60205999 1.        ]


In [50]:
## specialized versions that are useful for maintaining precision
## with very small input:

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
