In [1]:
import numpy as np

In [2]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [4]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [8]:
## data type

print("data type =", x3.dtype)

data type = int32


In [9]:
print("dtype:", x3.dtype)

dtype: int32


In [10]:
print ("itemsize =", x3.itemsize, "byte")

itemsize = 4 byte


In [11]:
print("nbyte =", x3.nbytes, "byte" )

nbyte = 240 byte


In [12]:
x3.itemsize * x3.size

240

In [13]:
x3.size

60

# Array Indexing: Accessing Single Elements

In [14]:
x1

array([5, 0, 3, 3, 7, 9])

In [15]:
x1[3]

3

In [16]:
## To index from the end of the array, you can use negative indices:

x1[-1]

9

In [17]:
x1[-3]

3

In [18]:
## In a multidimensional array, you access items using a comma-separated tuple of indices:

x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
x2[0,0] ## 3

3

In [20]:
x2[0, 1] ## row 0 column 1

5

In [21]:
## 8, row 1 column 2

x2[1, 2]

8

In [22]:
x2[2, -1] ## row 2 last column

7

In [23]:
## row 2 last column

x2[2, 3]

7

In [24]:
## You can also modify values using any of the above index notation:

x2 [0,0] = 12

In [25]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [26]:
## NumPy arrays have a fixed type

## that if you attempt to insert a floating-point value to an integer array, the
##value will be silently truncated.

x1[0] = 3.142

In [27]:
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

## x[start:stop:step]
## If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We’ll take a look at accessing subarrays in one dimension and in multiple dimensions.

## one dimentional array

In [28]:


A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
## Display first five

A[:5]

array([0, 1, 2, 3, 4])

In [30]:
## display element after index 5

A [5:]

array([5, 6, 7, 8, 9])

In [31]:
A[4:7] ## middle subarray start at index 4 end at 7


array([4, 5, 6])

In [32]:
A[::2] ## every elements in steps of 2

array([0, 2, 4, 6, 8])

In [33]:
A[1::2] ## EVERY ELEMENTS starting from 1 in steps of 2

array([1, 3, 5, 7, 9])

In [34]:
## A potentially confusing case is when the step value is negative. In this case, the
##defaults for start and stop are swapped.

A[::-1] ## all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
A[5::-2] ## reverse from index 5 in -2 increament

array([5, 3, 1])

## Multidimensional subarrays

In [36]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [37]:
## 2 rows 3 colums

x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [38]:
# all rows, every other column

x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [40]:
## subarray dimensions can even be reversed together:

x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

# Accessing array rows and columns.

In [41]:
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [42]:
# first column of x2

print(x2[:, 0] )

[12  7  1]


In [43]:
# first row of x2

print(x2[0, :])

[12  5  2  4]


In [44]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


In [45]:
## row 1

print(x2[1])

[7 6 8 8]


In [46]:
## column 2

print(x2[:, 2])

[2 8 7]


## Subarrays as no-copy views

### thing to know about array slices is that they return views rather than copies of the array data

In [47]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [51]:
## extracting 2x2 arrays

x2_sub = x2[:2, :2]

print(x2_sub)

[[12  5]
 [ 7  6]]


In [52]:
## Now if we modify this subarray, we’ll see that the original array is changed! Observe:

x2_sub[0, 0] = 99

In [54]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

In [55]:
## copy() method:

x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [56]:
### modify 

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [57]:
## check original

print(x2)  ## no change

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping of Arrays

In [58]:
## reshape() method

grid = np.arange(1, 10).reshape((3, 3))
print(grid)

## the size of the initial array must match the size of the reshaped array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
## conversion of a one-dimensional array into a two-dimensional row or column matrix.

x = np.array([1, 2, 3])

In [60]:
x

array([1, 2, 3])

In [61]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [62]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [63]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [64]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of arrays

### Concatenation, or joining of two arrays in NumPy, is primarily accomplishedthrough the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here:

In [65]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [66]:
## more than 2 arrays

z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [67]:
## two-dimensional arrays:

grid = np.array([[1, 2, 3],
                [4, 5, 6]])

In [68]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [70]:
## For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
## (vertical stack) and np.hstack (horizontal stack) functions:

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

In [71]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [76]:
## np.dstack will stack arrays along the third axis

np.dstack([grid, grid])

array([[[9, 9],
        [8, 8],
        [7, 7]],

       [[6, 6],
        [5, 5],
        [4, 4]]])

In [77]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

## Splitting of arrays

### The opposite of concatenation is splitting, which is implemented by the functions
### np.split, np.hsplit, and np.vsplit.

In [78]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [80]:
j = [2,4,5,6,7,8,9]
j1, j2, j3 = np.split(j, [2, 4])
print(j1, j2, j3)

[2 4] [5 6] [7 8 9]


In [81]:
## The related functions np.hsplit and np.vsplit are similar:

grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [83]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
