In [3]:
import numpy as np
np.random.seed(0)


def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
N = np.random.randint(1, 10, size=5)
N

array([7, 9, 9, 2, 7])

In [6]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.71 s ± 102 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
## Introducing UFuncs

print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [8]:
%timeit (1.0 / big_array)

4.27 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [12]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [13]:
x = np.arange(9).reshape((3, 3))

In [14]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])