In [1]:
import numpy as np

In [2]:
from scipy import special

In [3]:
# Gamma functions (generalized factorials) and related functions

x = [1, 5, 10]

In [4]:
print("gamma(x) =", special.gamma(x))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]


In [5]:
print("ln|gamma(x)| =", special.gammaln(x))

ln|gamma(x)| = [ 0.          3.17805383 12.80182748]


In [6]:
print("beta(x, 2) =", special.beta(x, 2))

beta(x, 2) = [0.5        0.03333333 0.00909091]


In [7]:
# Error function (integral of Gaussian)
# its complement, and its inverse

x = np.array([0, 0.3, 0.7, 1.0])

In [8]:
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


# Advanced Ufunc Features

## Specifying output

In [9]:
x = np.arange(5)
y = np.empty(5) ## empty array with similar xtics to x

In [11]:
x

array([0, 1, 2, 3, 4])

In [12]:
y

array([-4.58259161e-294,  1.46575171e+294,  2.95219319e+207,
       -8.15084784e-311,  0.00000000e+000])

In [13]:
np.multiply(x, 10, out=y) ## multiply x by 10 and save in y

array([ 0., 10., 20., 30., 40.])

In [14]:
print(y)

[ 0. 10. 20. 30. 40.]


In [15]:
## This can even be used with array views.

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


## Aggregates

In [16]:
## A reduce repeatedly applies a
## given operation to the elements of an array until only a single result remains.

## For example, calling reduce on the add ufunc returns the sum of all elements in the array:

x = np.arange(1, 6)
np.add.reduce(x) ## add all elements of list x

15

In [18]:
## Similarly, calling reduce on the multiply ufunc results in the product of all array elements:

np.multiply.reduce(x)

120

In [19]:
## If we’d like to store all the intermediate results of the computation, we can instead use accumulate:

np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [20]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

## Outer products

In [22]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [23]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Aggregations: Min, Max, and Everything in Between

## Summing the Values in an Array

In [24]:
L = np.random.random(100)
sum(L) ## python functioj

52.34288594477748

In [25]:
print(L)

[0.39869936 0.73378309 0.06160452 0.26082932 0.04686846 0.57954071
 0.72639592 0.85363041 0.7201679  0.65973922 0.79653066 0.98565717
 0.96049035 0.31926019 0.56544836 0.70515302 0.41725196 0.50479935
 0.82121004 0.68355527 0.50297201 0.80499275 0.24387915 0.28270828
 0.94846702 0.30286877 0.65382147 0.19651277 0.27593467 0.42229539
 0.93480882 0.58170187 0.05613201 0.14263203 0.46103759 0.29000315
 0.29276679 0.321902   0.88308568 0.05862608 0.99015755 0.38138348
 0.01172685 0.82783014 0.24258156 0.0804878  0.65672046 0.48863225
 0.95712078 0.35623077 0.00430565 0.83862759 0.37653012 0.95489184
 0.84934685 0.78757743 0.49798744 0.3453279  0.2943328  0.99771389
 0.58992545 0.46173763 0.58804454 0.30195883 0.42024332 0.88312537
 0.97044502 0.04961252 0.74176651 0.33074158 0.3995566  0.32443121
 0.81816882 0.1823629  0.73974915 0.50605097 0.57792736 0.05084052
 0.43368094 0.69799797 0.98233767 0.77452521 0.61600985 0.91060756
 0.27484871 0.28037051 0.24324952 0.48470593 0.94026872 0.9801

In [26]:
## numpy function

np.sum(L)

52.34288594477747

In [29]:
## numpy is faster

big_array = np.random.rand(1000000)
%timeit sum(big_array)

67.6 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%timeit np.sum(big_array)

644 µs ± 57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Minimum and Maximum

In [30]:
## Similarly, Python has built-in min and max functions, used to find the minimum value
## and maximum value of any given array:

min(big_array), max(big_array)

(5.670286538084213e-07, 0.9999995549204489)

In [31]:
## numpy

np.min(big_array), np.max(big_array)

(5.670286538084213e-07, 0.9999995549204489)

In [32]:
## np faster

%timeit min(big_array)
%timeit np.min(big_array)

44.6 ms ± 362 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
343 µs ± 3.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
## For min, max, sum, and several other NumPy aggregates, a shorter syntax is to use
## methods of the array object itself:

print(big_array.min(), big_array.max(), big_array.sum())

5.670286538084213e-07 0.9999995549204489 500093.69596544077


## Multidimensional aggregates

In [34]:
## 2 dimentional array

M = np.random.random((3, 4))
print(M)

[[0.13692235 0.80205093 0.91431484 0.93357356]
 [0.61733114 0.26933013 0.79202497 0.29794374]
 [0.51540868 0.37816522 0.50371774 0.39633606]]


In [35]:
## By default, each NumPy aggregation function will return the aggregate over the entire array:

M.sum()

6.557119362166494

In [40]:
## we can find the minimum value within each column by specifying axis=0:

print("min column =", M.min(axis=0))
print("Max column =", M.max(axis=0))

min column = [0.13692235 0.26933013 0.50371774 0.29794374]
Max column = [0.61733114 0.80205093 0.91431484 0.93357356]


In [41]:
## Similarly, we can find the maximum value within each row:

print("max row =", M.max(axis=1))
print("Min row =", M.min(axis=1))

max row = [0.93357356 0.79202497 0.51540868]
Min row = [0.13692235 0.26933013 0.37816522]


## exploring

In [43]:
import pandas as pd

In [56]:
data = pd.read_csv(r'C:\Users\RAC\Desktop\Data Science\Data\president_heights.csv')
data.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [57]:
heights = np.array(data['height(cm)'])

In [58]:
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [59]:
print("Mean Height =", heights.mean())

Mean Height = 179.73809523809524


In [61]:
print('Height Standard Deviation =', heights.std())

Height Standard Deviation = 6.931843442745892


In [62]:
print("Minimun Height =", heights.min())

Minimun Height = 163


In [63]:
print("Maximun Height =", heights.max())

Maximun Height = 193
